"""Render a structured FIR response into a downloadable PDF using ReportLab."""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib import colors


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "title", parent=base["Title"], fontSize=18, spaceAfter=18, alignment=1
        ),
        "h": ParagraphStyle(
            "h",
            parent=base["Heading2"],
            fontSize=12,
            spaceBefore=12,
            spaceAfter=6,
            textColor=colors.HexColor("#8a6d3b"),
        ),
        "body": ParagraphStyle(
            "body", parent=base["BodyText"], fontSize=10.5, leading=14, spaceAfter=6
        ),
        "small": ParagraphStyle(
            "small",
            parent=base["BodyText"],
            fontSize=9,
            leading=12,
            textColor=colors.grey,
        ),
    }


def render_fir_pdf(fir: dict[str, Any], complainant_name: str | None = None) -> bytes:
    """Return PDF bytes for a structured FIR response (postprocessor.data for FIR mode)."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title="FIR Draft - LegalEase AI",
    )
    s = _styles()
    story = []

    story.append(Paragraph(fir.get("fir_title") or "First Information Report (Draft)", s["title"]))

    meta_rows = [
        ["Generated by", "LegalEase AI"],
        ["Generated on", datetime.now().strftime("%d %B %Y, %H:%M IST")],
        ["Complainant", complainant_name or "—"],
    ]
    meta_table = Table(meta_rows, colWidths=[4 * cm, 12 * cm])
    meta_table.setStyle(
        TableStyle(
            [
                ("FONT", (0, 0), (-1, -1), "Helvetica", 9),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(meta_table)
    story.append(Spacer(1, 12))

    if fir.get("complainant_summary"):
        story.append(Paragraph("Complainant Summary", s["h"]))
        story.append(Paragraph(fir["complainant_summary"], s["body"]))

    if fir.get("incident_narrative"):
        story.append(Paragraph("Incident Narrative", s["h"]))
        story.append(Paragraph(fir["incident_narrative"], s["body"]))

    sections = fir.get("applicable_sections") or []
    if sections:
        story.append(Paragraph("Applicable Legal Provisions", s["h"]))
        rows = [["Act", "Section", "Offence"]]
        for sec in sections:
            rows.append(
                [
                    str(sec.get("act_name", "")),
                    str(sec.get("section", "")),
                    str(sec.get("offence", "")),
                ]
            )
        table = Table(rows, colWidths=[7 * cm, 3 * cm, 6 * cm], repeatRows=1)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a1a")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#d4af37")),
                    ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 10),
                    ("FONT", (0, 1), (-1, -1), "Helvetica", 9.5),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 8))

    if fir.get("police_station_guidance"):
        story.append(Paragraph("Police Station Guidance", s["h"]))
        story.append(Paragraph(fir["police_station_guidance"], s["body"]))

    evidence = fir.get("evidence_to_collect") or []
    if evidence:
        story.append(Paragraph("Evidence to Collect", s["h"]))
        for item in evidence:
            story.append(Paragraph(f"• {item}", s["body"]))

    warnings = fir.get("warnings") or []
    if warnings:
        story.append(Paragraph("Warnings & Disclaimers", s["h"]))
        for w in warnings:
            story.append(Paragraph(f"• {w}", s["small"]))

    story.append(Spacer(1, 18))
    story.append(
        Paragraph(
            "This document is an AI-generated draft. It must be reviewed by a "
            "licensed advocate before submission to any police authority.",
            s["small"],
        )
    )

    doc.build(story)
    return buf.getvalue()
